### ISSUE TITLE
Failed to load WebView provider: No WebView installed

### ISSUE THREAD

**Issue by giovanniPolatoO** [Tealium/tealium-kotlin#229]
In my project I've been reported some many crash about
`android.webkit.WebViewFactory$MissingWebViewPackageException - Failed to load WebView provider: No WebView installed`

Can you solve? Or tell me how to solve?

I already import via Gradle `implementation "androidx.webkit:webkit:1.7.0"`

OS: Android GO 11

**Comment by jameskeith** [comment]
Hi @giovanniPolatoO 

Do you happen to have a crash stack trace available for these incidents?

Also, are you able to confirm which version of the Tealium Kotlin SDK you are using? The only module we use a WebView in is `com.tealium:kotlin-tagmanagement-dispatcher` so the version of that artefact would be useful to know - the later versions should be catching exceptions thrown by WebView creation.

My understanding of this particular error is that the [System WebView Package](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US) is either not preset, disabled or is being updated at the time a WebView is being instantiated.

In those cases, I don't believe there is much we can do about it other than to catch and log the failure, then retry. I believe that v1.1.3+ of the TagManagement Dispatcher should already be doing that.

**Comment by giovanniPolatoO** [comment]
I use `com.tealium:kotlin-tagmanagement-dispatcher:1.2.1`.

`Fatal Exception: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
       at android.webkit.WebView.getFactory(WebView.java:2594)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2656)
       at android.view.View.<init>(View.java:5313)
       at android.view.View.<init>(View.java:5454)
       at android.view.ViewGroup.<init>(ViewGroup.java:703)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
       at android.webkit.WebView.<init>(WebView.java:421)
       at android.webkit.WebView.<init>(WebView.java:363)
       at android.webkit.WebView.<init>(WebView.java:345)
       at android.webkit.WebView.<init>(WebView.java:332)
       at android.webkit.WebView.<init>(WebView.java:322)
       **at com.tealium.tagmanagementdispatcher.d$b.invokeSuspend(d.java:4)**
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7886)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)`

**Comment by giovanniPolatoO** [comment]
This are all the implementation relative to Tealium in my build.gradle

```implementation 'com.tealium:kotlin-core:1.5.5'
    implementation 'com.tealium:kotlin-tagmanagement-dispatcher:1.2.1'
    implementation 'com.tealium:kotlin-lifecycle:1.2.0'
    implementation 'com.tealium:kotlin-ad-identifier:1.1.2'
    implementation 'com.android.installreferrer:installreferrer:2.2'
    implementation 'com.tealium:kotlin-location:1.1.2'
    implementation 'com.tealium:kotlin-remotecommand-dispatcher:1.3.1'
    implementation 'com.tealium:remotecommands:1.0.1'
    implementation 'com.tealium:kotlin-visitor-service:1.2.0'
    implementation 'com.tealium:kotlin-collect-dispatcher:1.1.1'

**Comment by jameskeith** [comment]
@giovanniPolatoO thanks for that - It's certainly possible that there's a conflict during resolution, and it's a little odd to see that there's no version specified for `com.tealium:kotlin-core`
Nevertheless, I've copied those dependencies into my test application but it correctly resolves to v1.2.1 of the TagManagement Dispatcher and the crash is therefore still not reproducible at my end.

Are you able to reproduce this at your end, or is it a report from users? 
Are you able to confirm whether or not this may be from a previous release of the app?

**Comment by giovanniPolatoO** [comment]
Sorry, I also implement `com.tealium:kotlin-core:1.5.5`

Unfortunately, I cannot reproduce the bug on my device.
However, all the reports received from crashlitics are from users who always have Android GO as their operating system

**Comment by jameskeith** [comment]
@giovanniPolatoO
Sorry to keep asking it, but is it possible that these crashes have come from an older app release? that had older Tealium versions?

I'm pretty confident that these crashes are resolved in the latest releases, and that the crash in question has come from an older version of our AAR's. 
It's pretty difficult to say for sure without knowing anything about the app itself, what it's release history is; what versions of Tealium have been published into the apk etc.

I don't have an Android GO device to hand, but the documentation doesn't specify that WebView is disabled by default:
https://developer.android.com/guide/topics/androidgo#differences-from-android
